### ISSUE TITLE
spectrum core

### ISSUE THREAD

**Issue by retro-pc** [piotr-go/FPGA#14]
- on latest version core spectrum.d19 Mar 15, 2024 i have black screen with red lines and not starting 
- on core spectrum.d19 previous version Oct 16, 2023 spectrum started ok
Next I copied the files on sd card with esxdos on FAT16/32 from http://www.esxdos.org/
when i trying run file browser .browse command or F11 key have a red lines on screen and freezes
I use 128-0.rom 128-1.rom ESXMMC.ROM and esxdos v085-089 
esxdos loading screen
![a65f7a64-f895-462f-889e-6df3c6f9ad4a](https://github.com/piotr-go/DIY-A586/assets/16412355/366fc808-669d-42f3-977c-a6e5da39a1e6)

**Comment by piotr-go** [comment]
Try:
https://github.com/piotr-go/DIY-A586/tree/master/v1.9/cores/spectrum/test

**Comment by retro-pc** [comment]
works

**Comment by retro-pc** [comment]
> Try: https://github.com/piotr-go/DIY-A586/tree/master/v1.9/cores/spectrum/test

works
