### ISSUE TITLE
Black borders on screen in amiga games

### ISSUE THREAD

**Issue by retro-pc** [piotr-go/FPGA#15]
when use "PrScr" different resolutions have different borders in games
examples in one res
![2024-05-13 19 35 37](https://github.com/piotr-go/DIY-A586/assets/16412355/6b293654-be77-4559-80c3-45e989964324)
![2024-05-13 19 35 48](https://github.com/piotr-go/DIY-A586/assets/16412355/a25c113b-6057-49bf-b165-9d5609e57701)

**Comment by piotr-go** [comment]
Added 640x400 cropping instead of one of the interlaced modes (but I may not keep this in future versions):
https://github.com/piotr-go/DIY-A586/blob/master/v1.9/cores/amiga/mikan/mikan_v0.1.7_640x400.d19
